# 
# The MonsterSpawn Configuration File
# 
# When  you use the /msmob command in game this file will be updated.
# You can also edit this file manually, but you will have to restart (or reload) the server.
