name: MonsterSpawn
version: 1.0
author: CrazyGriefer
main: me.crazygriefer.monsterspawn.Main
description: Will spawn a moster every 30 seconds!

commands:
  msstart:
    description: Start the spawning of the monster!
  msstop:
    description: Stops all the chaos.
  msmob: 
    description: /msmob <entity>. Select the entity that has to be spawned.
  msinterval:
    description: Change the interval between each spawn in seconds.